### ISSUE TITLE
Hidden Tabs and Tabs switching separate component

### ISSUE THREAD

**Issue by MykolaGolubyev** [testingisdocumenting/znai#288]
I have a use case where I want a user to select across two values: Java or Groovy and JUnit4 or JUnit5 or TestNG. So there are all these combinations. 

Instead of denormalizing all the combos I want to let a user select them independently. It can be achieved via nested tabs, but the look and feel is not going to be great.

What I propose is to let Tabs controller to be optionally invisible and provide an additional way to control Tabs. It can be a simple drop down. A sample Documentation would look something like this

```
Multiple test runners are supported. 
Example for `:tab-selection: JUnit 4, JUnit 5, Test NG` runner

```tabs
Groovy: ...
Java: ...
```
```

**Comment by jyeakel** [comment]
Just so I understand the proposed design, is the following what you suggest?

Introduce a `tab-selection` macro that can be included within existing `tabs` elements (e.g. "Java:", "Groovy:") and which is implemented as a drop down selector.

Seems reasonable, although do you have an implementation of the design you like? I agree nested tabs are undesirable, but since I assume you _will_ want to preserve the hierarchy and show the `tab-selection` selector as a nested element within the tabbed content, I wonder if introducing a different widget still creates a weird look and feel while also risking confusion because of the paradigm change.

**Comment by byc1234** [comment]
If you want to support :tab-selection:, I don't think that a global one as
in your example is useful. Most of the time, a user lists incompatible
languages like Java, cpp, and python in tabs.

**Comment by MykolaGolubyev** [comment]
@jyeakel not within the tabs, before Tabs. 

```
Multiple test runners are supported. 
Example for `:tab-selection: JUnit 4, JUnit 5, Test NG` runner

```tabs
Groovy: ...
Java: ...
```

![image](https://user-images.githubusercontent.com/11657860/67789314-2530f480-fa4a-11e9-984c-1b50fef2b45a.png)

**Comment by jyeakel** [comment]
I think allowing users to bury the configuration for a widget at any place they choose in a page is sort of dangerous from a usability perspective. I will mock an alternative design up and share it here.

**Comment by jyeakel** [comment]
The mockup below has two display options: one where the secondary options are beside the tabs; and another where they are within the tabs.

Nick, in your example I think you'd probably want the testing frameworks to be the primary tabs if you expect the testing framework to be the primary thing people are selecting on. Another part of your mockup that seemed potentially confusing to me was that, in the displayed output the testing framework seems to be the top part of the hierarchy since it's in the text above the tabs, but in the markdown it is the nested part. Hierarchy seems to switch from code to output.

![image001](https://user-images.githubusercontent.com/4038956/68035073-46d3eb00-fc99-11e9-85ee-62594842066b.png)

**Comment by MykolaGolubyev** [comment]
Oh nice. I think below is more scalable and mobile friendly. 
The reason I nest junit tabs in markdown is that those tabs are hidden and essentially only a selected tab (with drop down in my case) content will be displayed. But I guess it would work either way. 

So. We could change Tabs rendering component to figure rendering mode based on data provided. 
The only thing I know doubt is the syntax in markdown itself. It is much harder for human to read and write. But can be somewhat fixed using include-markdown or include-template I guess. And the case is quite rare. 

Should we consider a completely separate from tabs plugin? The one that has this use case in mind?

**Comment by MykolaGolubyev** [comment]
To make it easier for doc writers to define this kind of matrix selection I am thinking to introduce `multi-tabs` (name pending) separate plugin. It will work the same as tabs but will un-nest the definitions.

````
```multi-tabs
Groovy|Junit4:
Groovy|Junit5:
Groovy|TestNG:
Java|Junit4:
Java|Junit5:
Java|TestNG:
```
````

One drawback I can see right now is won't allow to have a common content for say `Groovy`  section before showing `JUnit4`, `JUnit5`, etc.

Thoughts @jyeakel?

**Comment by jyeakel** [comment]
I agree the nesting is messy in my mock-up that's just extending the current tabs convention, but is the nesting approach itself really the problem? I think that it makes sense to think of it as nesting conceptually, and if we go that way we can maintain a place for global top-level content, like you mention.

I know we should be mindful not to go nuts with new syntactic conventions, but what's wrong with something like:

`````
```multi-tabs
Groovy:
|Junit4:
Java:
|Junit4:
```
`````

or:

`````
```multi-tabs
Groovy:
::Junit4:
Java:
::Junit4:
```
`````

**Comment by MykolaGolubyev** [comment]
Nesting is the problem in case of nesting orignal `tabs` themselves.  Like in the example above.
If multi-tabs is a separate plugin, it shouldn’t be a problem to use whatever new syntax. 
Let’s zero in on the syntax. We can’t use spaces in front to denote a nest level as it will potentially clash with other syntax like `<space>Note: my notes` (If we don’t put space in front, Note becomes tab name).
Vertical pipe sort of makes sense and looks readable. 
If you are fine with vertical pipe lets also agree on design and dig into it!
Thanks @jyeakel  for providing alternative syntax.

**Comment by jyeakel** [comment]
I like the vertical pipe as well. It provides a good visual indent or inset without cluttering things up.

On design, because to date we have not made Znai particularly responsive, I would agree that placing the secondary tab selector under the primary tabs is the easiest scalable option. If things were responsive, I might suggest inline until vertical space required they be moved under the primary tabs (As mentioned before, the formatting options in these GitHub tabs follow this behavior, as an example)

**Comment by MykolaGolubyev** [comment]
closing this for now as my use cases were addressed in a different manner
