### ISSUE TITLE
tabs with spaces in preview crash the page

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/znai#647]
If I try and create tabs with a space in the tab name, it has some interesting effects.  I've only tried this in preview.

In the examples below I'm omitting the closing ```` because it seems to be really confusing the GitHub markdown renderer.

### Example 1 (correct behaviour):
```markdown
````tabs
One:
stuff

Two:
other stuff
```
![Screenshot 2021-06-28 at 16 30 53](https://user-images.githubusercontent.com/33879397/123663376-3db06e00-d82e-11eb-8605-5bc86a643af2.png)

### Example 2 (second tab has a space in the name):
```markdown
````tabs
One:
stuff

Two things:
other stuff
```
![Screenshot 2021-06-28 at 16 31 51](https://user-images.githubusercontent.com/33879397/123663502-5e78c380-d82e-11eb-898f-03ecb5cdace0.png)

### Example 3 (first tab has a space in the name):
```markdown
````tabs
One thing:
stuff

Two:
other stuff
```
![Screenshot 2021-06-28 at 16 33 03](https://user-images.githubusercontent.com/33879397/123663669-89631780-d82e-11eb-8aaa-0a2a457e7529.png)

### Example 4 (both have spaces):
```markdown
````tabs
One thing:
stuff

Two things:
other stuff
```
This just causes the page to crash.  I would paste the stack trace from the console but it's meaningless.

**Comment by davidskuza** [comment]
You could quote tab names with spaces.

Like:
```
````tabs
"One thing":
stuff

"Two things":
other stuff
```

**Comment by MykolaGolubyev** [comment]
@davidskuza sounds like a plan!
do you by any chance want to take a swing at it? I will be happy to help you along the way

**Comment by davidskuza** [comment]
I mean it's already working that way 😄 You can quote that string and it will work.

**Comment by MykolaGolubyev** [comment]
Got it :D 
this is what happens when something was added 3-4 years ago :)
Will try and update documentation to include this info

**Comment by MykolaGolubyev** [comment]
I still need to figure out why it crashes and print a link to the docs instead

**Comment by davidskuza** [comment]
Error is caused by https://github.com/testingisdocumenting/znai/blob/master/znai-reactjs/src/doc-elements/tabs/Tabs.js#L71. `tabsContent` is empty (when no correct Tab name while parsing was found) and no check is made. Parsing tab - content values is done by https://github.com/testingisdocumenting/znai/blob/master/znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/ColonDelimitedKeyValues.java#L82-L95 (extractKeyAndValuePart parses line of content to extract those key:values). It is used here https://github.com/testingisdocumenting/znai/blob/master/znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/tabs/TabsFencePlugin.java#L57-L73 and seems to work correctly. If no valid key found it returns `PluginResult` with type `Tabs` and empty `tabsContent`. So it seems that something on frontend/build/error has to be done to show the user that invalid `tabs` fence is provided.

**Comment by MykolaGolubyev** [comment]
@davidskuza thank you for looking into this. somehow I missed this comment.
I ended up forcing check on Java side by throwing the exception when no tab entries are present. 

You are pretty good at this. Are you using znai in your projects?

**Comment by davidskuza** [comment]
I am not using znai currently but will probably start to use it shortly.

**Comment by MykolaGolubyev** [comment]
@davidskuza I would like to chat to you more about documentation generation to learn about your ideas, use cases and potential showstoppers
let me know if this is of any interest. You can hit me here, LinkedIn, Telegram, etc
