### ISSUE TITLE
Question: Possible to include HTML in markdown?

### ISSUE THREAD

**Issue by uweschaefer** [testingisdocumenting/znai#661]
Hi

sorry if this is in the docs already and i was just too stupid to find it:

from my former SSG, i am used to be able to include the occasional `<a ...><img src="..." /></a>` into the markdown which then will not be transformed by the SSG.
One usecase would be to include the usual github/lab badges that everybody loves so much :laughing: 

Is there a was to do this/something similar in ZNAI ?

**Comment by MykolaGolubyev** [comment]
Hi,
sorry was traveling and forgot to reply.
Not possible to include HTML by design. Does `:include-image: url` works for you? If not, that is a regression and I will be happy to fix it.

Also had plans to have native support for GitHub metrics integration, but didn't have enough use cases for myself.
